version: 2
plugins:
  duplication:
    enabled: true
    exclude_patterns:
    - "__tests__/**"
    - "__mocks__/**"
    - "__fixtures__/**"
    - "**.spec.js"
  eslint:
    enabled: true
    exclude_patterns:
    - "__fixtures__/**"
exclude_patterns:
- "**.spec.js"
